### ISSUE TITLE
依赖包是否版本不对？

### ISSUE THREAD

**Issue by sumory** [ant-design/ant-design-pro-site#101]
> 环境
npm info using npm@5.5.1
npm info using node@v8.9.0

npm install后报warn

```
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN bisheng-plugin-antd@0.15.1 requires a peer of bisheng@^0.22.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@16.1.0 requires a peer of eslint-plugin-jsx-a11y@^6.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN postcss-modules-resolve-imports@1.3.0 requires a peer of postcss@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN dora-plugin-webpack@0.8.1 requires a peer of atool-build@0.x but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@1.6.1 requires a peer of webpack@1 || ^2.1.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself
```
npm start则直接报错
```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   '--verbose',
npm verb cli   'start' ]
npm info using npm@5.5.1
npm info using node@v8.9.0
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info lifecycle ant-design-pro-site@0.0.1~prestart: ant-design-pro-site@0.0.1
npm info lifecycle ant-design-pro-site@0.0.1~start: ant-design-pro-site@0.0.1

> ant-design-pro-site@0.0.1 start /data/tmp/ant-design-pro-site
> cross-env NODE_ENV=development bisheng start -c ./site/bisheng.config.js --no-livereload

           dora: listened on 8001
📦  1310/1326 build modules/data/tmp/ant-design-pro-site/node_modules/webpack/lib/Chunk.js:53
		throw new Error("Chunk.entry was removed. Use hasRuntime()");
		^

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.set entry [as entry] (/data/tmp/ant-design-pro-site/node_modules/webpack/lib/Chunk.js:53:9)
    at /data/tmp/ant-design-pro-site/node_modules/extract-text-webpack-plugin/index.js:216:26
    at Array.forEach (<anonymous>)
    at ExtractTextPlugin.<anonymous> (/data/tmp/ant-design-pro-site/node_modules/extract-text-webpack-plugin/index.js:211:11)
    at Compilation.applyPluginsAsync (/data/tmp/ant-design-pro-site/node_modules/atool-build/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.seal (/data/tmp/ant-design-pro-site/node_modules/atool-build/node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (/data/tmp/ant-design-pro-site/node_modules/atool-build/node_modules/webpack/lib/Compiler.js:397:15)
    at /data/tmp/ant-design-pro-site/node_modules/atool-build/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/data/tmp/ant-design-pro-site/node_modules/atool-build/node_modules/webpack/lib/Compilation.js:445:10)
    at /data/tmp/ant-design-pro-site/node_modules/atool-build/node_modules/webpack/lib/Compilation.js:417:12
npm verb lifecycle ant-design-pro-site@0.0.1~start: unsafe-perm in lifecycle true
```

**Comment by nikogu** [comment]
是 windows 环境吗？

**Comment by sumory** [comment]
macOS 10.12.5

**Comment by nikogu** [comment]
我本地换成跟你一样的版本，未能重现，正常跑起来了，你试试这个：https://github.com/webpack/webpack/issues/2764#issuecomment-232371501 手动改下依赖试试

**Comment by sumory** [comment]
- 一直在用cnpm
- 看了issue说的，但extract-text-webpack-plugin无论安装2.0.0的那个beta还是2.1.2，仍然报上面这个错误。我看webpack用的是3，而那个插件应该是兼容2的吧
- 已经换了一台电脑仍然报错，懒得挨个试了，建议看下包的兼容性

**Comment by nikogu** [comment]
我怀疑是 `webpack` 版本的问题，因为 `atool-build` 用的是 1.x 版本，如果你急用的话你可以尝试去掉当前 `webpack` 的依赖试试，不急的话，我明天调一调看看具体问题。

**Comment by sumory** [comment]
不急用，就是看到了想本地构建下来着，结果木有编出来。

**Comment by afc163** [comment]
试试 cnpm 看看是不是 cnpm 和 npm 不同的问题。

**Comment by sumory** [comment]
@afc163 我完全用cnpm install、cnpm start尝试也是这个错。
即使是使用工具的不同，但结果应该一致，否则cnpm的表现岂不是不符合预期了？

**Comment by oMaten** [comment]
```shell
cnpm uninstall webpack
cnpm i webpack@1
```

**Comment by sumory** [comment]
使用最新代码build，已经没有这个问题了👍

**Comment by kangfenmao** [comment]
参考这个：https://blog.kangfenmao.com/programming/npm-you-must-install-peer-dependencies-yourself.html
